// SPDX-License-Identifier: GPL-3.0-only
// Copyright 2026 SamGCoder
#include "../src/renderer_bridge.hpp"
#include "../src/dlss_bridge_channel.hpp"
#include <d3d12sdklayers.h>
#include <cstdio>
using namespace renderer_bridge;
constexpr UINT W=128,H=96;
struct TestGPU {
 ComPtr<ID3D12Device> gpu;ComPtr<ID3D12CommandQueue> queue;ComPtr<ID3D12CommandAllocator> allocator;ComPtr<ID3D12GraphicsCommandList> list;ComPtr<ID3D12Fence> fence;UINT64 serial{};
 ComPtr<ID3D12Resource> color,depth,mv,mask;MotionFlow flow;
 ComPtr<ID3D12Resource> texture(DXGI_FORMAT format,bool output=false){D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;d.Width=W;d.Height=H;d.DepthOrArraySize=1;d.MipLevels=1;d.Format=format;d.SampleDesc.Count=1;d.Flags=output?D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS:D3D12_RESOURCE_FLAG_NONE;ComPtr<ID3D12Resource> r;require(gpu->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_COMMON,nullptr,IID_PPV_ARGS(&r)),"Test texture");return r;}
 ComPtr<ID3D12Resource> buffer(UINT64 size,D3D12_HEAP_TYPE type){D3D12_HEAP_PROPERTIES hp{};hp.Type=type;D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=size;d.Height=1;d.DepthOrArraySize=1;d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;ComPtr<ID3D12Resource> r;require(gpu->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&d,type==D3D12_HEAP_TYPE_UPLOAD?D3D12_RESOURCE_STATE_GENERIC_READ:D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&r)),"Test buffer");return r;}
 TestGPU(){ComPtr<ID3D12Debug> debug;if(SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debug))))debug->EnableDebugLayer();require(D3D12CreateDevice(nullptr,D3D_FEATURE_LEVEL_11_0,IID_PPV_ARGS(&gpu)),"Test device");D3D12_COMMAND_QUEUE_DESC q{};require(gpu->CreateCommandQueue(&q,IID_PPV_ARGS(&queue)),"Test queue");require(gpu->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)),"Test allocator");require(gpu->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator.Get(),nullptr,IID_PPV_ARGS(&list)),"Test list");list->Close();gpu->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence));color=texture(DXGI_FORMAT_R8G8B8A8_UNORM);depth=texture(DXGI_FORMAT_R32_FLOAT);mv=texture(DXGI_FORMAT_R16G16_FLOAT,true);mask=texture(DXGI_FORMAT_R8_UNORM,true);flow.init(gpu.Get(),W,H);}
 void begin(){require(allocator->Reset(),"Test reset allocator");require(list->Reset(allocator.Get(),nullptr),"Test reset list");}
 void finish(){require(list->Close(),"Test close");ID3D12CommandList* lists[]{list.Get()};queue->ExecuteCommandLists(1,lists);require(queue->Signal(fence.Get(),++serial),"Test signal");Handle event;event.value=CreateEventW(nullptr,FALSE,FALSE,nullptr);fence->SetEventOnCompletion(serial,event.value);if(WaitForSingleObject(event.value,10000)!=WAIT_OBJECT_0)throw std::runtime_error("Test GPU timed out");}
 ComPtr<ID3D12Resource> upload(ID3D12Resource* destination,const void* data){auto desc=destination->GetDesc();D3D12_PLACED_SUBRESOURCE_FOOTPRINT footprint{};UINT64 size{};gpu->GetCopyableFootprints(&desc,0,1,0,&footprint,nullptr,nullptr,&size);auto staging=buffer(size,D3D12_HEAP_TYPE_UPLOAD);void* mapped{};staging->Map(0,nullptr,&mapped);for(UINT y=0;y<H;y++)memcpy(static_cast<char*>(mapped)+y*footprint.Footprint.RowPitch,static_cast<const char*>(data)+y*W*4,W*4);staging->Unmap(0,nullptr);D3D12_TEXTURE_COPY_LOCATION source{};source.pResource=staging.Get();source.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;source.PlacedFootprint=footprint;D3D12_TEXTURE_COPY_LOCATION target{};target.pResource=destination;target.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;transition(list.Get(),destination,D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_COPY_DEST);list->CopyTextureRegion(&target,0,0,0,&source,nullptr);transition(list.Get(),destination,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE);return staging;}
 std::vector<unsigned char> read(ID3D12Resource* source,UINT bytesPerPixel){auto desc=source->GetDesc();D3D12_PLACED_SUBRESOURCE_FOOTPRINT footprint{};UINT64 size{};gpu->GetCopyableFootprints(&desc,0,1,0,&footprint,nullptr,nullptr,&size);auto staging=buffer(size,D3D12_HEAP_TYPE_READBACK);begin();transition(list.Get(),source,D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_COPY_SOURCE);D3D12_TEXTURE_COPY_LOCATION a{};a.pResource=source;a.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;D3D12_TEXTURE_COPY_LOCATION b{};b.pResource=staging.Get();b.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;b.PlacedFootprint=footprint;list->CopyTextureRegion(&b,0,0,0,&a,nullptr);transition(list.Get(),source,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_COMMON);finish();void* mapped{};staging->Map(0,nullptr,&mapped);std::vector<unsigned char> out(W*H*bytesPerPixel);for(UINT y=0;y<H;y++)memcpy(out.data()+y*W*bytesPerPixel,static_cast<char*>(mapped)+y*footprint.Footprint.RowPitch,W*bytesPerPixel);staging->Unmap(0,nullptr);return out;}
 void frame(int offset,int lighting,bool reset=false){std::vector<unsigned> pixels(W*H);std::vector<float> depths(W*H,.8f);for(UINT y=0;y<H;y++)for(UINT x=0;x<W;x++){int value=32+lighting;if(int(x)>=32+offset&&int(x)<80+offset&&y>=24&&y<72){int local=int(x)-offset;value=60+((local*17+int(y)*31+(local/4)*47)%150);depths[y*W+x]=.4f;}pixels[y*W+x]=0xff000000u|value|(value<<8)|(value<<16);}begin();auto a=upload(color.Get(),pixels.data()),b=upload(depth.Get(),depths.data());MotionConstants c{W,H,reset?0u:1u,1};c.previousX[0]=1;c.previousY[1]=1;c.previousZ[2]=1;flow.record(list.Get(),color.Get(),depth.Get(),mv.Get(),mask.Get(),c,DXGI_FORMAT_R32_FLOAT);transition(list.Get(),color.Get(),D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COMMON);transition(list.Get(),depth.Get(),D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COMMON);finish();}
 void checkDebug(){ComPtr<ID3D12InfoQueue> info;if(SUCCEEDED(gpu.As(&info)))for(UINT64 i=0;i<info->GetNumStoredMessages();i++){SIZE_T n{};info->GetMessage(i,nullptr,&n);std::vector<char> storage(n);auto m=reinterpret_cast<D3D12_MESSAGE*>(storage.data());info->GetMessage(i,m,&n);if(m->Severity<=D3D12_MESSAGE_SEVERITY_ERROR){printf("%s\n",m->pDescription);throw std::runtime_error("D3D12 validation failed");}}}
};
float half(unsigned v){int exp=(v>>10)&31;float value=exp?std::ldexp(1.f+(v&1023)/1024.f,exp-15):std::ldexp(float(v&1023),-24);return v&32768?-value:value;}
int main(){try{TestGPU t;t.frame(0,0,true);auto masks=t.read(t.mask.Get(),1);for(auto m:masks)if(m!=255)throw std::runtime_error("First frame did not reject history");t.frame(4,0);auto vectors=t.read(t.mv.Get(),4);masks=t.read(t.mask.Get(),1);unsigned good=0,total=0;for(UINT y=32;y<64;y++)for(UINT x=44;x<72;x++){auto p=reinterpret_cast<const unsigned short*>(vectors.data()+(y*W+x)*4);float dx=half(p[0]),dy=half(p[1]);if(std::abs(dx+4)<1.1&&std::abs(dy)<1.1)good++;total++;}printf("Moving-object matches: %u/%u\n",good,total);if(good<total*7/10)throw std::runtime_error("Moving-object vectors incorrect");printf("Disocclusion mask %u, center %u\n",unsigned(masks[48*W+33]),unsigned(masks[48*W+52]));t.checkDebug();if(masks[48*W+33]<200)throw std::runtime_error("Disocclusion was not rejected");t.frame(4,50);vectors=t.read(t.mv.Get(),4);auto p=reinterpret_cast<const unsigned short*>(vectors.data()+10*W*4+10*4);if(half(p[0])!=0||half(p[1])!=0)throw std::runtime_error("Lighting change created false motion");t.frame(20,0,true);masks=t.read(t.mask.Get(),1);if(masks[48*W+55]!=255)throw std::runtime_error("Reset retained old history");t.frame(0,0,true);t.frame(16,0);vectors=t.read(t.mv.Get(),4);unsigned fast=0;for(UINT y=32;y<64;y++)for(UINT x=56;x<84;x++){auto v=reinterpret_cast<const unsigned short*>(vectors.data()+(y*W+x)*4);if(std::abs(half(v[0])+16)<1.2&&std::abs(half(v[1]))<1.2)fast++;}printf("Fast-motion matches: %u/896\n",fast);if(fast<627)throw std::runtime_error("Coarse-to-fine fast motion failed");t.checkDebug();printf("PASS: moving object, disocclusion, lighting-only change, reset, and D3D12 validation.\n");return 0;}catch(const std::exception& e){printf("FAIL: %s\n",e.what());return 1;}}
